{
    "cve": {
        "id": "CVE-2024-4109",
        "sourceIdentifier": "secalert@redhat.com",
        "published": "2024-12-12T09:15:06.207",
        "lastModified": "2024-12-12T09:15:06.207",
        "vulnStatus": "Received",
        "cveTags": [],
        "descriptions": [
            {
                "lang": "en",
                "value": "A flaw was found in Undertow. An HTTP request header value from a previous stream may be incorrectly reused for a request associated with a subsequent stream on the same HTTP/2 connection. This issue can potentially lead to information leakage between requests."
            },
            {
                "lang": "es",
                "value": "Se encontr\u00f3 un fallo en Undertow. Un valor de encabezado de solicitud HTTP de una secuencia anterior puede reutilizarse incorrectamente para una solicitud asociada con una secuencia posterior en la misma conexi\u00f3n HTTP/2. Este problema puede provocar una fuga de informaci\u00f3n entre solicitudes."
            }
        ],
        "metrics": {
            "cvssMetricV31": [
                {
                    "source": "secalert@redhat.com",
                    "type": "Primary",
                    "cvssData": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "attackVector": "NETWORK",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "NONE",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "NONE"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                }
            ]
        },
        "weaknesses": [
            {
                "source": "secalert@redhat.com",
                "type": "Primary",
                "description": [
                    {
                        "lang": "en",
                        "value": "CWE-200"
                    }
                ]
            }
        ],
        "references": [
            {
                "url": "https://access.redhat.com/security/cve/CVE-2024-4109",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2272325",
                "source": "secalert@redhat.com"
            }
        ]
    }
}